name: Publish Docs
on:
  push:
    branches:
      - docs-via-actions
#  release:
#    types: [published]
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew buildDocs
      # The following does the same as the docs:publish npm script, but in a GitHub actions environment
      - name: Push to GitHub Pages
        run: |
          cd thymeleaf-layout-dialect-docs/_book
          git init
          git checkout -b gh-pages
          touch .nojekyll
          git add .
          git -c user.name="Publish Docs action" -c user-email="emanuelrabina@gmail.com" commit -am 'Update docs'
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/ultraq/thymeleaf-layout-dialect.git gh-pages --force
